MEN-4382: Add deviceconfig service to the integration components
mendersoftware/integration pull request #1158
Opened 2021-01-21 13:04 UTC by alfrunes

2021-01-21 13:17 UTC, lluiscampos reviewed
Please do not merge this until the traefik PRs + mender-docs + the release is done :)

2021-01-22 07:15 UTC, kacf requested changes

2021-01-22 07:15 UTC, kacf commented on component-maps.yml
> +    release_component: true
You are missing an entry under the `docker_image` top level key. These blocks always come in threes.

2021-01-25 08:52 UTC, lluiscampos requested changes
Looks good to me otherwise.

2021-01-25 08:52 UTC, lluiscampos commented on docker-compose.config.yml
> +        image: mendersoftware/deviceconfig:master
The tag here should be `mender-master`

2021-01-25 09:30 UTC, mchalski commented on docker-compose.config.yml
> +        labels:
I'm here mostly for this section, +1 :)

2021-01-25 09:32 UTC, lluiscampos approved these changes

2021-01-26 08:46 UTC, lluiscampos commented
> Please do not merge this until the traefik PRs + mender-docs + the release is done :)

I won't block this any-more. Just coordinate with @kjaskiewiczz and the `mender-docs` test fixes.

2021-01-27 09:07 UTC, alfrunes commented
The [QA pipeline](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/246993880) with mendersoftware/mender-qa#477 passed.
@kacf I'm awaiting your second round of review before I'm merging all the deviceconfig integration PRs.

2021-01-28 14:49 UTC, kacf approved these changes
Perfect! Sorry for the delay!

2021-01-29 09:16 UTC, merged