MEN-5149 Azure IoT Manager repository added.
mendersoftware/integration pull request #1660
Opened 2021-10-18 19:25 UTC by merlin-northern

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2021-10-19 07:12 UTC, lluiscampos approved these changes

2021-10-19 07:30 UTC, kacf requested changes

2021-10-19 07:30 UTC, kacf commented on demo
> +            -f docker-compose.azure.yml \
Regarding the demo: Does this require extra steps to work, or is it just an additional component that is offered, but won't do anything unless you actively engage with it?

2021-10-19 07:30 UTC, kacf commented on component-maps.yml
> +    release_component: false
This is missing the corresponding `docker_image` and `docker_container` entries.

2021-10-20 06:55 UTC, kacf commented on component-maps.yml
> +    release_component: false
This should be set to true actually.

2021-10-20 07:07 UTC, merged