Unstable test upgrades
mendersoftware/integration pull request #2194
Opened 2022-10-18 10:46 UTC by MaciejTe

test(unstable): Mark test_upgrades as xfail

Changelog: None
Ticket: QA-451
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

2022-10-19 08:39 UTC, MaciejTe commented on tests/tests/test_access.py
> +    @pytest.mark.xfail(reason="QA-451")
No, if test case passes, pipeline won't fail. Basically, `xfail` marks test case as unstable. The pipeline won't fail if this TC fails

2022-10-19 09:12 UTC, oleorhagen commented on tests/tests/test_access.py
> +    @pytest.mark.xfail(reason="QA-451")
Oh, I misread it. It is marked as `xpass`

2022-10-19 09:17 UTC, oleorhagen requested changes
I don't think this is the way we should do it tbh.

1. I don't think we can simply mark this and close the ticket. The problem is still there.

2022-10-24 10:04 UTC, MaciejTe commented
As agreed during standup, I'm closing this task since it will be moved to backend integration tests.

2022-10-24 10:04 UTC, closed without merging