chore: migrated smtpd to aiosmtpd
mendersoftware/integration pull request #2541
Opened 2024-01-04 17:39 UTC by danielskinstad

Smtpd is fully removed in python3.12.
Moved from smtpd and asyncore to aiosmtpd.

Ticket: QA-603

2024-01-04 19:30 UTC, lluiscampos requested changes
It looks good! Thanks for doing this grunt work. I made some comments on minor things.

Remember that we need to add the dependency also in [here](https://github.com/mendersoftware/mender-test-containers/blob/master/backend-integration-testing/requirements-py3.txt) for the `backend-integration` tests to pass

2024-01-04 19:30 UTC, lluiscampos commented on tests/requirements-python/python-requirements.in
> +aiosmtpd==1.4.4.post2
Nitpick: missing newline

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +    async def handle_DATA(self, server, session, envelope):
I suggest we add here a reference to the documentation:
* https://aiosmtpd.readthedocs.io/en/stable/handlers.html#handle_DATA

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        return f"<Message peer={self.peer} mailfrom={self.mail_from} rcpttos={self.rcpttos} subject={self.subject}>"
Nice with the property rename. Please propagate it to the representation too:
```suggestion
        return f"<Message peer={self.peer} mail_from={self.mail_from} rcpttos={self.rcpttos} subject={self.subject}>"
```

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        logging.warning("got a message: %s" % mail_from)
Should this really be a warning? I think we should downgrade to `info`

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        logging.warning("got a message: %s" % mail_from)
Also, please remove the `%` construction when modernizing code. For logging it is better with:
```suggestion
        logging.warning("got a message:", mail_from)
```

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        logging.warning("got a message: %s" % mail_from)
Finally, maybe this should be "got a message from:"

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        self.messages.append(Message(peer, mail_from, rcpt_tos, None, data))
Why are we declaring all these local variables here? In my opinion it is better to do
```suggestion
        self.messages.append(Message(session.peer, envelope.mail_from, envelope.rcpt_tos, None, envelope.content))
```

2024-01-04 19:30 UTC, lluiscampos commented on testutils/infra/smtpd_mock.py
> +        return f"<Message peer={self.peer} mailfrom={self.mail_from} rcpttos={self.rcpttos} subject={self.subject}>"
Now that I see the rest of the code, I suggest we also here rename `rcpttos` to `rcpt_tos`

2024-01-05 14:19 UTC, danielskinstad commented
@mender-test-bot start pipeline

2024-01-08 09:45 UTC, merged